### ISSUE TITLE
Feature Report：In the top navigation, i hope to add a category navigation

### ISSUE THREAD

**Issue by znsee** [zwbetz-gh/papercss-hugo-theme#12]
## Concise Description
When there are a large number of articles， i need to quickly locate the content i want to read through the category navigation.
## Expect Description
After i added the category navigation in the configuration file, i don't knonw how to add the corresponding category page.
## Suggest Description
i hope you can teach me how to add such a category page with hierarchical relationships.
## Request Description
This theme is very good，and i like it very much.
i hope to join you in perfecting this theme.
Thanks a lot.

**Comment by zwbetz-gh** [comment]
Give this a try...

## Add the Taxonomy

Add categories as a taxonomy by changing this block:

https://github.com/zwbetz-gh/papercss-hugo-theme/blob/83b6770fa0eef20b860a6c77e4b42d240c95755a/exampleSite/config.yaml#L13-L14

To this:

```
taxonomies:
  tag: tags
  category: categories
```

## Update the Navigation

Add a link to the categories page by changing this block:

https://github.com/zwbetz-gh/papercss-hugo-theme/blob/83b6770fa0eef20b860a6c77e4b42d240c95755a/exampleSite/config.yaml#L31-L44

To this:

```
menu:
  nav:
    - name: Blog
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
```
